### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by martinhavens** [WowHesTall/Stratasys-Objet-Material-Bypass#1]
I'm a student working with an Objet260 system, if you have time to respond to some questions on your software with the system - that would be nice.

**Comment by martinhavens** [comment]
So, basically, I don't know how to use it or integrate it with my canisters or arduino controller.

**Comment by WowHesTall** [comment]
Hi, the uController plugs into the back of the PC on-board the Objet unit. In the maintenance mode of your printer control software, you may change the COM port used by the RFID reader to that of the uController. The uController replicates the responses of a cartridge the printer expects to "see".

Being that your system is an Objet 260, I cannot say if the protocol/commands are the same. Your best bet might be to install a COM monitoring utility to get a better idea what communication is happening between the printer and the RFID reader module.

Good luck!

**Comment by martinhavens** [comment]
Thank you WowHesTall - It does not seem the Objet260 has either a COM port or maintenance mode :>

To be honest, we don't even have the printer in hand yet and still LOL. If it's OK with you, I will be referencing your work in our student project, but will likely go the opposite route of wireless protocol communication. In my dreams, when we have the printer in hand, I will find a COM port leading to the RFID module for the Objet260.

**Comment by martinhavens** [comment]
Would you know why our [Sparkfun RFID Kit](https://www.sparkfun.com/products/15209) will not currently read the material cartridges? I'm not sure if your prior experience would be able to help us with that. 
Both seem to operate on the 125kHz band, my thoughts are perhaps we need to use Aluminum foil to create an antenna and if that's the problem thank the world.

We've also found out the chip internal to our system is a[ HITAG HTRC11001T](https://www.mouser.com/ProductDetail/NXP-Semiconductors/HTRC11001T-03EE11/?qs=me8TqzrmIYXFfehhhz6%2FBA%3D%3D ), we bought a [surface mount to breakout board ](https://www.digikey.com/en/products/detail/PA0003/PA0003-ND/5014719?utm_medium=email&utm_source=oce&utm_campaign=3480_OCE21RT&utm_content=productdetail_US&utm_cid=1674813&so=67760484&mkt_tok=eyJpIjoiWWpjek1qYzNaamhtWkRCaCIsInQiOiJRU0ZBY2l4WGRBQkM1dG5tZjFFVVdcL3J2UmtFN1RlRTFnOElzNzc3NVpXeFA3NCtRaWdoMms1clRuNGtXYUdGdmc3QXV1NndpdW9IU3Z1VXlRODdzZmdwaDJvMUNOMHNOTnAxbGplT0Q1ZGxZWFA4aGc2NkZxOEVEcWsyZ3UxT20ifQ%3D%3D) adapter as well. Hope those work together and can transmit/transpond (idk a difference) similar code to what you have laid out on your GitHub. Honestly beautiful work, thank you.
